### PR TITLE
Issue-31 - Added link to CA

### PR DESCRIPTION
**Pull request by M-casado**
Both Silvia and I added some context to the Collaboration Agreement (CA) to the legal-governance section of the ReadTheDocs.

## Description
* Added link of the Collaboration Agreement to https://ega-archive.github.io/FEGA-onboarding/topics/governance-legal/#fega-collaboration-agreement
* Added context of the current version of the CA to https://ega-archive.github.io/FEGA-onboarding/topics/governance-legal/#fega-collaboration-agreement

## Motivation and Context
* New link of the CA was available.

## How has this been tested?
* Tested format and content change in my forked GitHub Pages: https://m-casado.github.io/FEGA-onboarding/topics/governance-legal/#2-implement-legal-frameworks

## What should reviewers focus on?
* The Link works and redirects to the current CA version
* Context of the version is self explanatory and easy to understand.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change which adds new content)
- [x] Modified content (non-breaking change which modifies existing content)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] I have read the CONTRIBUTING.md guide.
- [x] My changes follow the code style of this project.
- [x] I have updated supporting documentation, if required.
- [x] I have added my details to the CONTRIBUTORS.yaml file.

### CODE REVIEW

**Review by silviabah — APPROVED** [review]
The modification is the same as: https://m-casado.github.io/FEGA-onboarding/topics/governance-legal/#2-implement-legal-frameworks

Where the link works correctly and the context was added :)

**Comment by malloryfreeberg** [comment]
- Checked @M-casado 's fork and the link and context look good to me 👍 
- One request: Since @silviabah helped with this change/PR, can the [contributor list](https://github.com/EGA-archive/FEGA-onboarding/blob/main/CONTRIBUTORS.yaml) please be updated with her details as part of this PR?

**Review by malloryfreeberg — CHANGES_REQUESTED** [review]
- Checked @M-casado 's fork and the link and context look good to me 👍
- One request: Since @silviabah helped with this change/PR, can the [contributor list](https://github.com/EGA-archive/FEGA-onboarding/blob/main/CONTRIBUTORS.yaml) please be updated with her details as part of this PR?

**Comment by M-casado** [comment]
Done, @malloryfreeberg  👍

**Review by malloryfreeberg — APPROVED** [review]
LGTM!

**Pull request merged**
