### PR TITLE
More readable text with list of general topics

### PR DESCRIPTION
**Pull request by jmenglund**
I made some changes to the section "How do I start?" on the from page to make the text more readable. I basically simplified the text and reformatted it as a list of general topics/areas.

### CODE REVIEW

**Review by malloryfreeberg — CHANGES_REQUESTED** [review]
Excellent - thank you so much for your contribution! 

Can you do a quick rebase to the current main branch? We recently updated the root dir for the website, and now the root is `docs/`. Which means the relative references (*I think*) need to start with `topics/`.

**Comment by jmenglund** [comment]
My branch is up to date, so it doesn't seems a rebase will solve this.

I see that there are two files `index.md`; one directly under the repository's root and one under `docs/'. I made the changes to the first mentioned.

I can try to make the same changes to the file `docs/index.md` instead (and discard the changes to the other file). Would that be ok?

**Comment by malloryfreeberg** [comment]
Hi @jmenglund - good catch. Indeed, the file `docs/index.md` is the one that needs to be updated (I didn't catch that when I reviewed). Since we set the website root to `docs/`, it only sees files in that directory. 

In this case, can you do as you suggested and make your proposed changes in the `docs/index.md` file. I'll raise a ticket to delete the `index.md` file in the root dir. 

Have a lovely weekend!

**Comment by jmenglund** [comment]
I have now made the changes to the other file instead.

**Review by malloryfreeberg — APPROVED** [review]
Looks great @jmenglund ! Thank you for your contribution :)

**Pull request merged**
